In [ ]:
'''
전체 회원의 2005년도 4월 구매일자에 대한 구매수량의 합을 조회하세요
구매일자는 장바구니 테이블에서 주문번호 앞 8자리 입니다
구매수량은 장바구니 테이블에서 수량을 의미합니다
회원 ID, 회원성명, 구매수량의 합 조회
구매수량이 없으면 0으로 처리
'''

In [ ]:
'''
select mem_id, mem_name, 
       sum(nvl(cart_qty,0)) as cart_sqty
from member left outer join cart
            on(mem_id = cart_member and
               substr(cart_no, 1, 6) = '200504')      
group by mem_id, mem_name
'''

In [ ]:
'''
select A.mem_id, A.mem_name, 
       sum(nvl(B.cart_qty,0)) as cart_sqty
from member A left outer join cart B
            on(A.mem_id = B.cart_member and
               substr(B.cart_no, 1, 6) = '200504')      
group by A.mem_id, A.mem_name
order by A.mem_id, A.mem_name
'''

# 함수

In [96]:
import cx_Oracle as ora
import pandas as pd

# 오라클 연결/접속/커서
def setDsn() :
    return ora.makedsn('localhost', 1521, service_name = 'orcl')

def setConn(dsn) :
    return ora.connect('busan_06', 'dbdb', dsn)

def setCur(conn) :
    return conn.cursor()

# 오라클 커서 반납, 접속 끊기
def closeOracle(cur, conn) :
    cur.close()
    conn.close()

# 데이터 가져오기
def getFetchall(query, cur) :
    cur.execute(query)
    return cur.fetchall()

# 데이터프레임 만들기
def getCol(cur) :
    col = []
    for i in cur.description :
        col.append(i[0])
    return col

def getDF(row, col) :
    return pd.DataFrame(row, columns=col)

# 최종 호출함수
def getAll(query) :
    dsn = setDsn()
    conn = setConn(dsn)
    cur = setCur(conn)
    row = getFetchall(query, cur)
    col = getCol(cur)
    closeOracle(cur, conn)
    return getDF(row, col)

## 함수 사용

In [99]:
query = """ select * from member """

getAll(query)

,MEM_ID,MEM_PASS,MEM_NAME,MEM_REGNO1,MEM_REGNO2,MEM_BIR,MEM_ZIP,MEM_ADD1,MEM_ADD2,MEM_HOMETEL,MEM_COMTEL,MEM_HP,MEM_MAIL,MEM_JOB,MEM_LIKE,MEM_MEMORIAL,MEM_MEMORIALDAY,MEM_MILEAGE,MEM_DELETE
0,a001,asdfasdf,김은대,760115,1406420,1976-01-15,135-972,대전시 동구 용운동,222-2번지,042-621-4615,042-621-4615,011-621-4615,pyoedab@lycos.co.kr,주부,수영,결혼기념일,1999-01-12,1000,None
1,b001,1004,이쁜이,741004,2900000,1974-01-07,700-030,서울시 천사동 예쁜마을,1004-29,02-888-9999,02-888-9999,016-888-9999,engelcd@pretty.net,회사원,수영,아버님생신,1999-02-12,2300,None
2,c001,7777,신용환,740124,1400716,1974-01-24,407-817,대전광역시 중구 대흥동,477-9,042-123-5678,042-123-5678,011-123-5678,kyh01e@hanmail.net,교사,독서,아내생일,1999-03-12,3500,None
3,d001,123joy,성윤미,460409,2000000,1946-04-09,501-705,대전시 중구 하늘동,땅 3번지,042-222-8877,042-222-8877,019-222-8877,dbs81f@hanmail.net,공무원,볼링,결혼기념일,1999-04-12,1700,None
4,e001,00000000,이혜나,750501,2406017,1975-05-01,617-800,대전시 대덕구 읍내동,혜강아파트,042-432-8901,042-432-8901,011-432-8901,bosiang@hanmail.net,농업,당구,아버님생신,1999-05-12,6500,None
5,f001,12345678,신영남,751228,1459919,1972-11-04,140-706,대전광역시 대흥동,65-33 303호,042-253-2121,042-253-2121,011-253-2121,SUPER-KHG@HANMAIL.NET,주부,볼링,아내생일,1999-06-12,2700,None
6,g001,1456,송경희,771111,2403414,1965-01-01,339-841,충남금산군 제원면,심내리123-1,0412-356-3578,0412-356-3578,017-356-3578,lim052@hanmail.net,주부,스키,결혼기념일,1999-07-12,800,None
7,h001,9999,라준호,740728,1455822,1967-03-01,339-841,충남 논산시 양촌면,산직3구 345,042-522-1679,042-522-1679,019-522-1679,wingl7@hanmail.net,회사원,독서,아내생일,1999-08-12,1500,None
8,i001,1111,최지현,741220,2384719,1974-12-20,306-702,대전시 동구 가양1동,768-12,042-614-6914,042-614-6914,017-614-6914,pan@orgio.net,공무원,등산,남편생일,1999-09-12,900,None
9,j001,6262,김윤희,751019,2448920,1975-11-21,306-702,대전시 서구 삼천동,한신아파트305동309호,042-332-8976,042-332-8976,018-332-8976,maxsys@hanmail.net,농업,개그,결혼기념일,1999-10-12,1100,None
10,k001,7227,오철희,620123,1449311,1962-01-23,306-702,대전시 대덕구 대화동,34-567,042-157-8765,042-157-8765,016-157-8765,equus@orgio.net,자영업,서예,아내생일,1999-11-12,3700,None
11,l001,12345678,구길동,881214,1234566,1988-12-14,339-841,충남금산군 금산읍,하리35-322,0412-322-8865,0412-322-8865,016-322-8865,email815@hanmail.co.kr,자영업,바둑,결혼기념일,1999-12-12,5300,None
12,m001,pass,박지은,750315,2555555,1975-03-15,306-702,대전광역시 서구 갈마동,인성아파트 234동 907호,042-252-0675,042-252-0675,016-252-0675,happy@hanmail.net,은행원,등산,아버님생신,1999-12-12,1300,None
13,n001,1111,탁원재,750323,1011014,1975-03-23,306-702,대전시 동구 자양동,32-23,042-632-2176,042-632-2176,019-632-2176,ping75@unitel.co.kr,축산업,낚시,결혼기념일,1999-02-12,2700,None
14,o001,0909,배인정,780930,2447619,1978-09-30,306-702,대전시 서구 갈마동,경성아파트502동1101호,042-622-5971,042-622-5971,011-622-5971,tar-song@hanmail.net,회사원,등산,어머님생신,1999-03-12,2600,None
15,p001,sahra3,오성순,730805,2458323,1973-08-05,306-702,대전유성구송강동,한솔아파트 703동 407호,042-810-7658,042-810-7658,017-810-7658,sahra235@intz.com,공무원,독서,남편생일,1999-05-12,2200,None
16,q001,0000,육평회,721020,1402722,1972-10-20,306-702,대구광역시 대덕구 중리동,678-43,042-823-2359,042-823-2359,017-823-2359,kph@hanmail.net,자영업,만화,결혼기념일,1999-06-12,1500,None
17,r001,park1005,정은실,770120,2382532,1976-11-26,306-702,대전시 동구 용전동,321-25,042-533-8768,042-533-8768,016-533-8768,econie@hanmail.net,학생,장기,어머님생신,1999-07-12,700,None
18,s001,0819,안은정,770819,2459927,1977-10-01,306-702,대구광역시 서구 탄방동,산호아파트 107동 802호,042-222-8155,042-222-8155,019-222-8155,songej@hanmail.net,공무원,바둑,결혼기념일,1999-07-12,3200,None
19,t001,0506,성원태,760506,1454731,1976-05-06,306-702,대전광역시 중구 유천동,한사랑아파트 302동 504호,042-272-8657,042-272-8657,011-272-8657,bob6@hanmail.net,학생,카레이싱,결혼기념일,1999-08-12,2200,None
20,u001,1000,김성욱,731010,1460111,1973-10-10,306-702,대전시 동구 용전동,76-54,042-273-9056,042-273-9056,018-273-9056,pss576@orgio.net,주부,영화감상,결혼기념일,1999-07-12,2700,None
21,v001,00001111,이진영,520131,2402712,1952-01-31,306-702,대전시 동구 용전동,566-39번지,042-240-8766,042-240-8766,017-240-8766,gagsong@orgio.net,자영업,낚시,남편생일,1999-09-12,4300,None
22,w001,12341234,김형모,631213,1111111,1963-12-13,306-702,대전시 대덕구 연축동,23-43,02-345-9877,02-345-9877,011-345-9877,songone@hanmail.net,학생,등산,결혼기념일,1999-11-12,2700,None
23,x001,0000,진현경,770319,2110222,1977-03-19,306-702,대전광역시 동구 오정동,43-26,042-223-8767,042-223-8767,019-223-8767,happysong@hanmail.net,주부,독서,결혼기념일,1999-02-12,8700,None

## 기존 코드

In [ ]:
dsn = ora.makedsn('localhost', 1521, service_name = 'orcl')
conn = ora.connect('busan_06', 'dbdb', dsn)
cur = conn.cursor()

cur = initOralcle()

query = """ select mem_id, mem_name, 
       sum(nvl(cart_qty,0)) as cart_sqty
from member left outer join cart
            on(mem_id = cart_member and
               substr(cart_no, 1, 6) = '200504')      
group by mem_id, mem_name """

cur.execute(query)
row = cur.fetchall()
colname = cur.description

cur.close()
conn.close()

col = []
for i in colname :
    col.append(i[0])
col

pd.DataFrame(row, columns=col)